### ISSUE TITLE
Update to uglify-es

### ISSUE THREAD

**Issue by tomkel** [TrySound/rollup-plugin-uglify#30]
Uglify-es 3.0 supports es6 syntax.

https://github.com/mishoo/UglifyJS2/releases

**Comment by TrySound** [comment]
Fixed in v2

**Comment by tomkel** [comment]
Yes, but this plugin still doesn't have es6 syntax support. You need to use the harmony branch of uglify, published as `uglify-es`.

**Comment by TrySound** [comment]
@tomkel Yes, Because uglify-es is unstable. That's why it has own package name,
